import { IsString, MinLength, MaxLength } from 'class-validator';

export class PasswordLoginDto {
  @IsString()
  @MinLength(3)
  @MaxLength(120)
  username!: string; // phone or email

  @IsString()
  @MinLength(1)
  @MaxLength(200)
  password!: string;
}

export class RefreshDto {
  @IsString()
  @MinLength(20)
  refreshToken!: string;
}

export class VerifyOtpDto {
  /**
   * Firebase ID token obtained on the device after a successful OTP confirm.
   * Generated by `confirmation.confirm(code).then(user => user.getIdToken())`
   * on React Native Firebase.
   */
  @IsString()
  @MinLength(50)
  firebaseIdToken!: string;
}
